name: Code style

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm ci

      - name: Run prettier
        run: npm run format

      - name: Commit actions
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier styles
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
