name: Code style

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Run prettier
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: format

      - name: Commit actions
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier styles
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
